# Hostname of the manager and the compute nodes.
hostname_manager: sandboxController

# The domain names and ips to add in the no_proxy variable (comma separated)
#user_domains: 1.1.1.1

# The passwort that should be used for the system user 'stack'.
stack_password: secretsecret

# The password that should be used for services like the database or queuing.
service_password: secretsecret

# The password that should be used for the OpenStack admin user.
admin_password: secretsecret

# The public SSH key that should be used for the system user 'stack'.
#stack_sshkey: the_ssh_public_key_you_want_for_your_stack_user

# Define the setup mode to install the environment.
# valid values: grenade, devstack
# default value: devstack
setup_mode: devstack

# What interface on the host should be used for a bridge will often be eth0,
# but vagrant needs to know for sure. This needs to be the full string
# descriptor of the interface. On some systems this can be something annoying
# like 'en1: Wi-Fi (Airport)'. Vagrant will not use this setting unless you get
# it exactly right.
bridge_int: eth0

# A non upstream for the base box, used to speed things up. Choose one of
# box_name (for a locally added box) or box_url for the url of a nearby box.
box_name: 'bento/ubuntu-18.04'
#box_name: 'bento-xenial64'
#box_name: 'geerlingguy/ubuntu1604'
#box_version: '1.0.6'
#box_url: http://gallifrey/vagrant/devstack-2014-02-19.box

# Vagrant username used in box image, e.g. ubuntu
vagrant_username: vagrant

# Non upstream Git URL to fetch Devstack from instead.
#devstack_git: /home/vagrant/openstack/devstack

# If you have code on a different branch than master, you can set it here.
#devstack_branch: stable/pike

# You can specify a proxy, for example https://github.com/tmatilai/polipo-box,
# to be used for HTTP connections to speed things up.
#proxy: http://1.1.1.1:8080

# Uncomment below to setup LDAP on the management node and use it as backend
# for keystone.
#use_ldap: true

# You can specify stable MAC addresses to keep this from resetting on every
# create.
#mac_address_manager: 0800274a508c
#mac_address_compute: 0800274a508d

# It is possible to use a hostonly-network instead of a bridged network when
# setting the parameter use_bridge to false.
use_bridge: false

# When using a hostonly-network it is possible to specify static IP addresses
# using the following parameters. If those parameters are not specified DHCP
# will be used.
ip_address_manager: 10.0.20.10

# floating ip range for guests
floating_range: 10.0.20.0/24
public_network_gateway: 10.0.20.1
floating_allocation_pool_start: 10.0.20.40
floating_allocation_pool_end: 10.0.20.254

# Name of network interface in virtual machine - e.g. enp0s8 in ubuntu
guest_interface_default: eth1
host_ip_iface: eth1

# Extra images to download and add to glance, a list of url's comma separated
# for new images to be added to glance
#extra_images: https://cloud-images.ubuntu.com/precise/current/precise-server-cloudimg-amd64-disk1.img,https://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img

export_dir: /opt/stack
